version: '3'

services:

    mongodb:
        restart: unless-stopped
        ports:
            - 127.0.0.1:27017:27017
        image: mongo:4.2.12
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - mongodb-data:/data/db

volumes:
    mongodb-data: